version: "3.9"

services:
  # Caddy + X-UI 容器网络模式设置为 host，从而允许通过修改配置的方式使用任意端口，无须修改容器

  caddy:
    image: "caddy:latest"
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
      # - ./site:/srv   # 静态网页文件,如有
    network_mode: host

  xui:
    # 选择喜欢的镜像
    image: "enwaiax/x-ui:latest"    # vaxilu/x-ui
    # image: "enwaiax/x-ui:alpha-zh"  # FranzKafkaYu/x-ui
    # image: "enwaiax/x-ui:beta"      # X-UI-Unofficial/x-ui
    container_name: xui
    restart: always
    volumes:
      - ./xui_data:/etc/x-ui/
      # - ./xui_ssl:/root/cert/   # TLS 证书，用于 HTTPS 直接访问 X-UI
    network_mode: host

  # 选择喜欢的项目作为伪装，本示例为 Rickroll
  rickroll:
    image: "modem7/docker-rickroll:latest"
    container_name: rickroll
    ports:
      - "127.0.0.1:8080:8080"   # 映射至宿主机 8080 端口
    environment:
      - TITLE="You are Rickrolled! :-P"